VetApp/config/routes.rb
VetApp::Application.routes.draw do
  root 'welcome#start'
  resources :records
  resources :appointments
  resources :doctors
  
  get 'doctors' => 'doctor#index'
  get 'appointment' => 'appointments#index'
  get 'appointment/list' => 'appointments#list', :as => "list"
  get 'records' => 'record#index'

  

end

VetApp/app/models/appointment.rb
class Appointment < ActiveRecord::Base
  validates :date_of_visit, presence: true
  validates :pet, presence: true
  validates :customer, presence: true
  validates :visit_reason, presence: true
  validate :date_check
  
  def date_check
    if self.date_of_visit < Date.today
      errors.add(:date_of_visit, 'The appointment date can\'t be in the past.')
    end
  end
  
  def self.search(query)
    where("pet like ?", "%#{query}%") 
  end
end

VetApp/app/models/doctor.rb
class Doctor < ActiveRecord::Base
  has_many :appointments
  validates :name,  presence: true, length: { maximum: 35, message: "Name can't be longer than 35 characters." }
  validates :zip, length: { maximum: 5 }
  validates_inclusion_of :years_of_experience, {:in => 1..100, :message => "Years of experience must be between 1 and 100."}
end

VetApp/app/models/record.rb
class Record < ActiveRecord::Base
  validates :pet_name, presence: true, length: { maximum: 35, message: "Pet name can't be longer than 35 characters." }
  validates :pet_type, presence: true
  validates_inclusion_of :pet_type, :in => %w(dog cat bird)
  validates :breed, presence: true, length: { maximum: 35, message: "Breed can't be longer than 35 characters." }
  validates :age, presence: true
  validates :weight, presence: true
  validates :last_visit_date, presence: true
end

VetApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

VetApp/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @appointment }
      else
        format.html { render action: 'new' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url }
      format.json { head :no_content }
    end
  end
  
  def list
    @appointments = Appointment.where(['date_of_visit >= ?', DateTime.now]) 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:date_of_visit, :pet, :customer, :appointment_reminder, :visit_reason)
    end
end

VetApp/app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :edit, :update, :destroy]

  # GET /doctors
  # GET /doctors.json
  def index
    @doctors = Doctor.all
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show
  end

  # GET /doctors/new
  def new
    @doctor = Doctor.new
  end

  # GET /doctors/1/edit
  def edit
  end

  # POST /doctors
  # POST /doctors.json
  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to @doctor, notice: 'Doctor was successfully created.' }
        format.json { render action: 'show', status: :created, location: @doctor }
      else
        format.html { render action: 'new' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to @doctor, notice: 'Doctor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    @doctor.destroy
    respond_to do |format|
      format.html { redirect_to doctors_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def doctor_params
      params.require(:doctor).permit(:name, :address, :city, :state, :zip, :school_degree_from, :years_of_experience)
    end
end

VetApp/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
  end

  # GET /records/1
  # GET /records/1.json
  def show
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)

    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render action: 'show', status: :created, location: @record }
      else
        format.html { render action: 'new' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:pet_name, :pet_type, :breed, :age, :weight, :last_visit_date)
    end
end

VetApp/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def start
  end
end

VetApp/app/helpers/application_helper.rb
module ApplicationHelper
end

VetApp/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

VetApp/app/helpers/doctors_helper.rb
module DoctorsHelper
end

VetApp/app/helpers/records_helper.rb
module RecordsHelper
end

VetApp/app/helpers/welcome_helper.rb
module WelcomeHelper
end

VetApp/app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_visit %><br>
    <%= f.date_select :date_of_visit %>
  </div>
  <div class="field">
    <%= f.label :pet %><br>
    <%= f.text_field :pet %>
  </div>
  <div class="field">
    <%= f.label :customer %><br>
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :appointment_reminder %><br>
    <%= f.check_box :appointment_reminder %>
  </div>
  <div class="field">
    <%= f.label :visit_reason %><br>
    <%= f.text_field :visit_reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

VetApp/app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'form' %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

VetApp/app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Date of visit</th>
      <th>Pet</th>
      <th>Customer</th>
      <th>Appointment reminder</th>
      <th>Visit reason</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.date_of_visit %></td>
        <td><%= appointment.pet %></td>
        <td><%= appointment.customer %></td>
        <td><%= appointment.appointment_reminder %></td>
        <td><%= appointment.visit_reason %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

VetApp/app/views/appointments/list.html.erb
<h1>Appointments</h1>

<% @appointments.each do |appointment| %>
    <h3>Pet Name: <%= appointment.pet %></h3>
    <p>Next Visit: <%= appointment.date_of_visit %></p>
    <p>Visit Reason: <%= appointment.visit_reason %></p>
<% end %>

VetApp/app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', appointments_path %>

VetApp/app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of visit:</strong>
  <%= @appointment.date_of_visit %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @appointment.pet %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @appointment.customer %>
</p>

<p>
  <strong>Appointment reminder:</strong>
  <%= @appointment.appointment_reminder %>
</p>

<p>
  <strong>Visit reason:</strong>
  <%= @appointment.visit_reason %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>

VetApp/app/views/doctors/_form.html.erb
<%= form_for(@doctor) do |f| %>
  <% if @doctor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@doctor.errors.count, "error") %> prohibited this doctor from being saved:</h2>

      <ul>
      <% @doctor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :school_degree_from %><br>
    <%= f.text_field :school_degree_from %>
  </div>
  <div class="field">
    <%= f.label :years_of_experience %><br>
    <%= f.number_field :years_of_experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

VetApp/app/views/doctors/edit.html.erb
<h1>Editing doctor</h1>

<%= render 'form' %>

<%= link_to 'Show', @doctor %> |
<%= link_to 'Back', doctors_path %>

VetApp/app/views/doctors/index.html.erb
<h1>Listing doctors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>School degree from</th>
      <th>Years of experience</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @doctors.each do |doctor| %>
      <tr>
        <td><%= doctor.name %></td>
        <td><%= doctor.address %></td>
        <td><%= doctor.city %></td>
        <td><%= doctor.state %></td>
        <td><%= doctor.zip %></td>
        <td><%= doctor.school_degree_from %></td>
        <td><%= doctor.years_of_experience %></td>
        <td><%= link_to 'Show', doctor %></td>
        <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
        <td><%= link_to 'Destroy', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Doctor', new_doctor_path %>

VetApp/app/views/doctors/new.html.erb
<h1>New doctor</h1>

<%= render 'form' %>

<%= link_to 'Back', doctors_path %>

VetApp/app/views/doctors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @doctor.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @doctor.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @doctor.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @doctor.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @doctor.zip %>
</p>

<p>
  <strong>School degree from:</strong>
  <%= @doctor.school_degree_from %>
</p>

<p>
  <strong>Years of experience:</strong>
  <%= @doctor.years_of_experience %>
</p>

<%= link_to 'Edit', edit_doctor_path(@doctor) %> |
<%= link_to 'Back', doctors_path %>

VetApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VetApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

VetApp/app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pet_name %><br>
    <%= f.text_field :pet_name %>
  </div>
  <div class="field">
    <%= f.label :pet_type %><br>
    <%= f.text_field :pet_type %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :last_visit_date %><br>
    <%= f.date_select :last_visit_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

VetApp/app/views/records/edit.html.erb
<h1>Editing record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

VetApp/app/views/records/index.html.erb
<h1>Listing records</h1>

<table>
  <thead>
    <tr>
      <th>Pet name</th>
      <th>Pet type</th>
      <th>Breed</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Last visit date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.pet_name %></td>
        <td><%= record.pet_type %></td>
        <td><%= record.breed %></td>
        <td><%= record.age %></td>
        <td><%= record.weight %></td>
        <td><%= record.last_visit_date %></td>
        <td><%= link_to 'Show', record %></td>
        <td><%= link_to 'Edit', edit_record_path(record) %></td>
        <td><%= link_to 'Destroy', record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Record', new_record_path %>

VetApp/app/views/records/new.html.erb
<h1>New record</h1>

<%= render 'form' %>

<%= link_to 'Back', records_path %>

VetApp/app/views/records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Pet name:</strong>
  <%= @record.pet_name %>
</p>

<p>
  <strong>Pet type:</strong>
  <%= @record.pet_type %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @record.breed %>
</p>

<p>
  <strong>Age:</strong>
  <%= @record.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @record.weight %>
</p>

<p>
  <strong>Last visit date:</strong>
  <%= @record.last_visit_date %>
</p>

<%= link_to 'Edit', edit_record_path(@record) %> |
<%= link_to 'Back', records_path %>

VetApp/app/views/welcome/index.html.erb
<h1>Welcome to the Sterling Animal Clinic Website</h1>
<p><%= link_to "Doctor", :controller => :doctor, :action => :index %></p>

VetApp/app/views/welcome/start.html.erb
<h1>Welcome to the Sterling Animal Clinic Website</h1>
<p><%= link_to "Receptionist", :controller => :appointments, :action => :index %></p>
<p><%= link_to "Doctor", :controller => :record, :action => :index %></p>
<p><%= link_to "Owner", :controller => :doctor, :action => :index %></p>
<p><%= link_to "Customer", :list %></p>